### ISSUE TITLE
Trying to search in invoices but always my fields "are not set"

### ISSUE THREAD

**Issue by araeubig** [onlime/bexio-api-client#3]
Sorry for disturbing with perhaps a very silly question, but i can't see actually my error:

I try to search for invoices with this code:

```
<?php

require_once '../vendor/autoload.php';
require_once 'bexio-api.php';

use Bexio\Client;
use Bexio\Resource\Invoice;

$client = new Client($clientId, $clientSecret);
$client->loadTokens($tokensFile);

$bexioInvoice = new Invoice($client);

//$invoices = $bexioInvoice->getInvoices();


$params = array(
    "field" => "kb_item_status_id",
    "value" => "8",
    "criteria" => "="
);

$invoices = $bexioInvoice->searchInvoices($params);

echo "<pre>";
print_r($invoices);
echo "</pre>";
```

But i always get this error:

`Fatal error: Uncaught Bexio\Exception\BexioClientException: The following search parameters could not have been applied: ["field not set","field not set","field not set"] in /workspaces/bexio-stripe-pos-backend/www/vendor/onlime/bexio-api-client/src/Bexio/Client.php on line 63 Bexio\Exception\BexioClientException: The following search parameters could not have been applied: ["field not set","field not set","field not set"] in /workspaces/bexio-stripe-pos-backend/www/vendor/onlime/bexio-api-client/src/Bexio/Client.php on line 63 Call Stack: 0.0003 474576 1. {main}() /workspaces/bexio-stripe-pos-backend/www/bexio-v2/invoices.php:0 0.0011 575328 2. Bexio\Resource\Invoice->searchInvoices($params = ['field' => 'kb_item_status_id', 'value' => '8', 'criteria' => '='], $queryParams = ???) /workspaces/bexio-stripe-pos-backend/www/bexio-v2/invoices.php:23 0.0011 575328 3. Bexio\Client->post($path = 'kb_invoice/search', $data = ['field' => 'kb_item_status_id', 'value' => '8', 'criteria' => '='], $queryParams = []) /workspaces/bexio-stripe-pos-backend/www/vendor/onlime/bexio-api-client/src/Bexio/Resource/Invoice.php:22 0.0011 575328 4. Bexio\Client->request($path = 'kb_invoice/search', $method = 'POST', $data = ['field' => 'kb_item_status_id', 'value' => '8', 'criteria' => '='], $queryParams = []) /workspaces/bexio-stripe-pos-backend/www/vendor/onlime/bexio-api-client/src/Bexio/Client.php:18`

It would be great to get a small hint - Thank you very much.

Regards André

**Comment by onlime** [comment]
Hey @araeubig ! Sorry for the delay - Github didn't notify me about this issue.
I am doing the same in my helper class:

```php
class InvoiceExtended extends Invoice
{
    public function searchInvoicesByStatus(int $statusId)
    {
        return $this->searchInvoices([
            [
                'field'    => 'kb_item_status_id',
                'value'    => $statusId,
                'criteria' => '=',
            ],
        ]);
    }
    // ...
```

Ah, just figured it out! You need to wrap the search params into an extra array, so instead do this (and please don't use the legacy `array()` syntax in PHP... just a detail):

```php
$params = [
    [
        "field" => "kb_item_status_id",
        "value" => "8",
        "criteria" => "="
    ],
];
```

Also see **Code example (PHP)** on [Bexio API docs > Search](https://docs.bexio.com/#section/API-basics/Search), where you see that they support multiple searches (treated as `AND`), also wrapped in an array.

Cheers, Philip
